[workspace]
members = [
  "crates/client/db",
  "crates/client/exec",
  "crates/client/sync",
  "crates/client/eth",
  "crates/client/rpc",
  "crates/client/gateway/client",
  "crates/client/gateway/server",
  "crates/client/analytics",
  "crates/client/telemetry",
  "crates/client/devnet",
  "crates/client/mempool",
  "crates/client/block_import",
  "crates/node",
  "crates/primitives/block",
  "crates/primitives/convert",
  "crates/primitives/transactions",
  "crates/primitives/class",
  "crates/primitives/gateway",
  "crates/primitives/receipt",
  "crates/primitives/state_update",
  "crates/primitives/chain_config",
  "crates/primitives/utils",
  "crates/client/aptos",
  "crates/proc-macros",
  "crates/tests",
  "crates/cairo-test-contracts",
]
resolver = "2"
# Everything except test-related packages, so that they are not compiled when doing `cargo build`.
default-members = [
  "crates/client/aptos",
  "crates/client/db",
  "crates/client/exec",
  "crates/client/sync",
  "crates/client/eth",
  "crates/client/gateway/client",
  "crates/client/gateway/server",
  "crates/client/rpc",
  "crates/client/telemetry",
  "crates/client/devnet",
  "crates/client/mempool",
  "crates/client/block_import",
  "crates/client/analytics",
  "crates/node",
  "crates/primitives/block",
  "crates/primitives/convert",
  "crates/primitives/transactions",
  "crates/primitives/class",
  "crates/primitives/gateway",
  "crates/primitives/receipt",
  "crates/primitives/state_update",
  "crates/primitives/chain_config",
  "crates/primitives/utils",
  "crates/proc-macros",
]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
print_stdout = "warn"
print_stderr = "warn"
# todo: uncomment these & fix them
# unwrap_used = "warn"
# missing_docs = "warn"

[profile.dev]
incremental = true

[profile.release]
panic = "unwind"

[profile.production]
codegen-units = 1    # Setting this to 1 allows for more optimizations at the cost of slower compile time
inherits = "release"
lto = "fat"          # Enables Link Time Optimization, enabling more aggressive optimizations across the entire codebase
opt-level = 3        # Optimize for speed regardless of binary size or compile time
rpath = false        # Disables adding rpath to the binary
strip = "symbols"    # Removes debug info and symbold from final binary

[workspace.package]
authors = ["Madara <https://github.com/madara-alliance>"]
homepage = "https://madara.build"
edition = "2021"
repository = "https://github.com/madara-alliance/madara/"
version = "0.7.0"
license = "Apache-2.0"

[workspace.dependencies]
rocksdb = { version = "0.22", features = [
  # "multi-threaded-cf",
] }

# Bonsai trie dependencies
bonsai-trie = { default-features = false, git = "https://github.com/cchudant/bonsai-trie.git", branch = "fix_inserts_remove_leaks", features = [
  "std",
] }

# Madara proc macros
m-proc-macros = { path = "crates/proc-macros", default-features = false }

# Madara primtitives
mp-block = { path = "crates/primitives/block", default-features = false }
mp-convert = { path = "crates/primitives/convert", default-features = false }
mp-transactions = { path = "crates/primitives/transactions", default-features = false }
mp-class = { path = "crates/primitives/class", default-features = false }
mp-gateway = { path = "crates/primitives/gateway", default-features = false }
mp-receipt = { path = "crates/primitives/receipt", default-features = false }
mp-state-update = { path = "crates/primitives/state_update", default-features = false }
mp-utils = { path = "crates/primitives/utils", default-features = false }
mp-chain-config = { path = "crates/primitives/chain_config", default-features = false }

# Madara client
mc-aptos = { path = "crates/client/aptos" }
mc-analytics = { path = "crates/client/analytics" }
mc-telemetry = { path = "crates/client/telemetry" }
mc-db = { path = "crates/client/db" }
mc-exec = { path = "crates/client/exec" }
mc-rpc = { path = "crates/client/rpc" }
mc-gateway-client = { path = "crates/client/gateway/client" }
mc-gateway-server = { path = "crates/client/gateway/server" }
mc-sync = { path = "crates/client/sync" }
mc-eth = { path = "crates/client/eth" }
mc-mempool = { path = "crates/client/mempool" }
mc-block-import = { path = "crates/client/block_import" }
mc-devnet = { path = "crates/client/devnet" }

# Madara misc
m-cairo-test-contracts = { path = "crates/cairo-test-contracts" }

# Starknet dependencies
cairo-vm = "=1.0.1"
starknet-core = "0.12"
starknet-crypto = "0.7"
starknet-providers = "0.12"
starknet-signers = "0.10"
starknet = "0.12.0"

starknet-types-core = { version = "0.1.7", default-features = false, features = [
  "hash",
] }
starknet-types-rpc = "0.7.1"

blockifier = "=0.8.0"
starknet_api = "=0.13.0-rc.1"
cairo-lang-starknet-classes = "=2.8.4"
cairo-lang-utils = "=2.8.4"

alloy = { version = "0.4.0", features = [
  "node-bindings",
  "rpc-types",
  "provider-http",
  "contract",
  "node-bindings",
] }

# Other third party dependencies
paste = "1.0.15"
anyhow = "1.0"
assert_matches = "1.5"
async-trait = "0.1"
sha3 = "0.10"
bitvec = { version = "1.0", default-features = false, features = ["std"] }
clap = { version = "4.4" }
flate2 = "1.0"
futures = { version = "0.3", default-features = false, features = ["std"] }
jsonrpsee = { version = "0.22", default-features = false, features = [
  "server",
  "client",
] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["cors"] }
governor = "0.6"
hyper = { version = "1.5.0", features = ["full"] }
hyper-tls = "0.6"
hyper-util = "0.1.9"
http = "1.1.0"
http-body-util = "0.1.2"
ip_network = "0.4"
lazy_static = { version = "1.4", default-features = false }
once_cell = "1.19"
num-traits = "0.2"
num-bigint = "0.4"
primitive-types = "0.12"
rand = "0.8"
indoc = "2"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rstest = "0.18"
serde = { version = "1.0", default-features = false, features = ["std"] }
serde_with = "3.9"
serde_json = { version = "1.0", default-features = false, features = ["std"] }
serde_yaml = { version = "0.9.34" }
thiserror = "1.0"
tokio = { version = "1.34", features = ["signal", "rt"] }
url = { version = "2.4", features = ["serde"] }
rayon = "1.10"
bincode = "1.3"
fdlimit = "0.3.0"
proptest = "1.5.0"
proptest-derive = "0.5.0"
dotenv = "0.15.0"
httpmock = "0.7.0"
tempfile = "3.10.1"
mockall = "0.13.0"
serial_test = "3.1.1"
itertools = "0.13.0"
regex = "1.10.5"
bytes = "1.6.0"
crypto-bigint = "0.5.5"

# Instrumentation
opentelemetry = { version = "0.25.0", features = ["metrics", "logs"] }
opentelemetry_sdk = { version = "0.25.0", features = ["rt-tokio", "logs"] }
opentelemetry-stdout = { version = "0.25.0" }
opentelemetry-otlp = { version = "0.25.0", features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { version = "0.25.0" }
opentelemetry-appender-tracing = { version = "0.25.0", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-core = { version = "0.1.32", default-features = false }
tracing-subscriber = { version = "0.3.18", features = [
  "env-filter",
  "registry",
  "std",
] }
tracing-opentelemetry = "0.26.0"

aptos-sdk = { git = "https://github.com/aptos-labs/aptos-core", rev = "6a130c1cca274a5cfdb4a65b441cd5fe61b6c15b", package = "aptos-sdk"  }

[patch.crates-io]
# wait for PR https://github.com/starknet-io/types-rs/pull/76 to be merged
starknet-types-core = { git = "https://github.com/kasarlabs/types-rs.git", branch = "feat-deserialize-v0.1.7" }

blockifier = { git = "https://github.com/starkware-libs/blockifier", tag = "v0.8.0-rc.0" }

merlin = { git = "https://github.com/aptos-labs/merlin" }
x25519-dalek = { git = "https://github.com/Tranduy1dol/x25519-dalek", branch = "zeroize_v1.7" }
